# Generated by Django 5.0.4 on 2024-05-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='license',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
