# Generated by Django 5.0.4 on 2024-05-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver_is_online_driver_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='license',
        ),
        migrations.AddField(
            model_name='driver',
            name='car_license',
            field=models.ImageField(null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_license',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
