# Generated by Django 5.0.4 on 2024-06-01 02:06

import driver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_remove_driver_license_driver_car_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=driver.models.generate_random_rating),
        ),
    ]
