# Generated by Django 5.0.4 on 2024-06-02 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_driver_city'),
        ('driver', '0004_driver_rating'),
    ]

    operations = [
    ]
