# Generated by Django 5.0.4 on 2024-06-07 10:01

import driver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_alter_driver_car_license_alter_driver_driver_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='actual_car_license',
            field=models.CharField(default=driver.models.generate_random_license, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='truck',
            field=models.CharField(default='Honda Ridgeline', max_length=100),
        ),
    ]
