# Generated by Django 5.0.4 on 2024-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_alter_driver_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='truck',
            field=models.CharField(default='Jeep Gladiator', max_length=100),
        ),
    ]
