# Generated by Django 5.0.4 on 2024-05-02 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preferred_method', models.CharField(choices=[(1, 'Cash on Delivery'), (2, 'Mobile Banking'), (3, 'Credit or Debit Card')], max_length=50)),
            ],
        ),
    ]
