# Generated by Django 5.0.4 on 2024-06-01 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('driver', '0003_remove_driver_license_driver_car_license_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('withdraw', 'Withdraw'), ('deposit', 'Deposit')], max_length=100)),
                ('payment_method', models.CharField(choices=[(1, 'Cash on Delivery'), (2, 'Mobile Banking'), (3, 'Credit or Debit Card')], max_length=100)),
                ('To_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_driver', to='driver.driver')),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_customer', to='customer.customer')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
