# Generated by Django 5.0.4 on 2024-05-05 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('multiple commodities', 'Multiple Commodities '), ('food', 'Food'), ('plastic&rubber', 'Plastic and Rubber'), ('appliances', 'Appliances'), ('glass', 'Glass'), ('furniture', 'Furinture'), ('wood', 'Wood')], max_length=200)),
                ('pickup_time', models.DateTimeField()),
                ('need_packing', models.BooleanField()),
                ('need_labor', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
