# Generated by Django 5.0.4 on 2024-05-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(4, 'tricycle 2700 kg'), (1, 'jumbo box 2700 kg'), (2, 'jumbo box 5200 kg'), (3, 'jumbo box 5200 kg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('plastic&rubber', 'Plastic and Rubber'), ('food', 'Food'), ('appliances', 'Appliances'), ('furniture', 'Furinture'), ('wood', 'Wood'), ('glass', 'Glass'), ('multiple commodities', 'Multiple Commodities ')], max_length=200),
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
