# Generated by Django 5.0.4 on 2024-05-05 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_chosen_truck_alter_orders_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pickup_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='time_created',
            field=models.TimeField(default=datetime.time(21, 57, 53, 640626)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(3, 'jumbo box 5200 kg'), (4, 'tricycle 2700 kg'), (1, 'jumbo box 2700 kg'), (2, 'jumbo box 5200 kg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pickup_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('food', 'Food'), ('plastic&rubber', 'Plastic and Rubber'), ('appliances', 'Appliances'), ('glass', 'Glass'), ('wood', 'Wood'), ('multiple commodities', 'Multiple Commodities '), ('furniture', 'Furinture')], max_length=200),
        ),
    ]
