# Generated by Django 5.0.4 on 2024-06-01 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_pickup_date_orders_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(4, 'tricycle 2700 kg'), (3, 'jumbo box 5200 kg'), (1, 'jumbo box 2700 kg'), (2, 'jumbo box 5200 kg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time_created',
            field=models.TimeField(default=datetime.time(5, 6, 7, 718991)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('glass', 'Glass'), ('furniture', 'Furinture'), ('wood', 'Wood'), ('appliances', 'Appliances'), ('multiple commodities', 'Multiple Commodities '), ('food', 'Food'), ('plastic&rubber', 'Plastic and Rubber')], max_length=200),
        ),
    ]
