# Generated by Django 5.0.4 on 2024-06-01 01:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_pickup_date_orders_time_created_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_transaction', to='payment.transactions'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(1, 'jumbo box 2700 kg'), (4, 'tricycle 2700 kg'), (2, 'jumbo box 5200 kg'), (3, 'jumbo box 5200 kg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time_created',
            field=models.TimeField(default=datetime.time(4, 46, 2, 358193)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('wood', 'Wood'), ('furniture', 'Furinture'), ('glass', 'Glass'), ('appliances', 'Appliances'), ('food', 'Food'), ('multiple commodities', 'Multiple Commodities '), ('plastic&rubber', 'Plastic and Rubber')], max_length=200),
        ),
    ]
