# Generated by Django 5.0.4 on 2024-05-29 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_chosen_truck_alter_orders_order_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(3, 'jumbo box 5200 kg'), (1, 'jumbo box 2700 kg'), (4, 'tricycle 2700 kg'), (2, 'jumbo box 5200 kg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('confirmed', 'Confirmed'), ('pickup', 'Pickup'), ('assigned', 'Assigned'), ('delivered', 'Delivered')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time_created',
            field=models.TimeField(default=datetime.time(16, 33, 34, 644835)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('appliances', 'Appliances'), ('multiple commodities', 'Multiple Commodities '), ('food', 'Food'), ('glass', 'Glass'), ('furniture', 'Furinture'), ('wood', 'Wood'), ('plastic&rubber', 'Plastic and Rubber')], max_length=200),
        ),
    ]
