# Generated by Django 5.0.4 on 2024-06-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_dropoff_location_orders_pickup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pricing',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(4, 'tricycle 2700 kg'), (3, 'jumbo box 5200 kg'), (2, 'jumbo box 5200 kg'), (1, 'jumbo box 2700 kg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('delivered', 'Delivered'), ('unassigned', 'Unassigned'), ('confirmed', 'Confirmed'), ('pickup', 'Pickup')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('multiple commodities', 'Multiple Commodities '), ('glass', 'Glass'), ('appliances', 'Appliances'), ('food', 'Food'), ('furniture', 'Furinture'), ('plastic&rubber', 'Plastic and Rubber'), ('wood', 'Wood')], max_length=200),
        ),
    ]
