# Generated by Django 5.0.4 on 2024-06-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_dropoff_location_orders_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(3, 'jumbo box 5200 kg'), (4, 'tricycle 2700 kg'), (1, 'jumbo box 2700 kg'), (2, 'jumbo box 5200 kg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('delivered', 'Delivered'), ('confirmed', 'Confirmed'), ('pickup', 'Pickup')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('plastic&rubber', 'Plastic and Rubber'), ('appliances', 'Appliances'), ('food', 'Food'), ('wood', 'Wood'), ('multiple commodities', 'Multiple Commodities '), ('glass', 'Glass'), ('furniture', 'Furinture')], max_length=200),
        ),
    ]
