# Generated by Django 5.0.4 on 2024-06-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orders_pricing_alter_orders_chosen_truck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(3, 'jumbo box 5200 kg'), (4, 'tricycle 2700 kg'), (1, 'jumbo box 2700 kg'), (2, 'jumbo box 5200 kg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('confirmed', 'Confirmed'), ('unassigned', 'Unassigned'), ('delivered', 'Delivered'), ('pickup', 'Pickup')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('wood', 'Wood'), ('furniture', 'Furinture'), ('multiple commodities', 'Multiple Commodities '), ('glass', 'Glass'), ('plastic&rubber', 'Plastic and Rubber'), ('food', 'Food'), ('appliances', 'Appliances')], max_length=200),
        ),
    ]
