# Generated by Django 5.0.4 on 2024-06-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orders_delivery_date_orders_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(1, 'small truck'), (3, 'special large truck'), (2, 'large truck'), (4, 'tricycle')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('delivered', 'Delivered'), ('assigned', 'Assigned'), ('pickup', 'Pickup'), ('unassigned', 'Unassigned')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('glass', 'Glass'), ('wood', 'Wood'), ('plastic&rubber', 'Plastic and Rubber'), ('food', 'Food'), ('furniture', 'Furinture'), ('multiple commodities', 'Multiple Commodities '), ('appliances', 'Appliances')], max_length=200),
        ),
    ]
