# Generated by Django 5.0.4 on 2024-06-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orders_chosen_truck_alter_orders_order_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(3, 'special large truck'), (4, 'tricycle'), (2, 'large truck'), (1, 'small truck')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='commodity_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned'), ('delivered', 'Delivered'), ('unassigned', 'Unassigned')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('multiple commodities', 'Multiple Commodities '), ('food', 'Food'), ('glass', 'Glass'), ('wood', 'Wood'), ('plastic&rubber', 'Plastic and Rubber'), ('appliances', 'Appliances'), ('furniture', 'Furinture')], max_length=200),
        ),
    ]
