# Generated by Django 5.0.4 on 2024-06-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orders_chosen_truck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(1, 'small truck'), (3, 'special large truck'), (2, 'large truck'), (4, 'tricycle')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('unassigned', 'Unassigned'), ('pickup', 'Pickup'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('appliances', 'Appliances'), ('plastic&rubber', 'Plastic and Rubber'), ('furniture', 'Furinture'), ('multiple commodities', 'Multiple Commodities '), ('glass', 'Glass'), ('wood', 'Wood'), ('food', 'Food')], max_length=200),
        ),
    ]
