# Generated by Django 5.0.4 on 2024-06-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orders_chosen_truck_alter_orders_order_state_and_more'),
        ('orders', '0013_alter_orders_chosen_truck_alter_orders_order_state_and_more'),
    ]

    operations = [
    ]
