# Generated by Django 5.0.4 on 2024-06-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_merge_20240608_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='weight',
            field=models.FloatField(default=5.2),
        ),
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(3, 'special large truck'), (4, 'tricycle'), (1, 'small truck'), (2, 'large truck')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivered', 'Delivered'), ('assigned', 'Assigned'), ('confirmed', 'Confirmed'), ('unassigned', 'Unassigned')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('wood', 'Wood'), ('glass', 'Glass'), ('appliances', 'Appliances'), ('plastic&rubber', 'Plastic and Rubber'), ('multiple commodities', 'Multiple Commodities '), ('furniture', 'Furinture'), ('food', 'Food')], max_length=200),
        ),
    ]
