# Generated by Django 5.0.4 on 2024-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orders_weight_alter_orders_chosen_truck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(4, 'tricycle'), (3, 'special large truck'), (2, 'large truck'), (1, 'small truck')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('delivered', 'Delivered'), ('confirmed', 'Confirmed'), ('pickup', 'Pickup')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('furniture', 'Furinture'), ('wood', 'Wood'), ('multiple commodities', 'Multiple Commodities '), ('appliances', 'Appliances'), ('glass', 'Glass'), ('plastic&rubber', 'Plastic and Rubber'), ('food', 'Food')], default='plastic&rubber', max_length=200),
        ),
    ]
