# Generated by Django 5.0.4 on 2024-06-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_transaction_alter_orders_chosen_truck_and_more'),
        ('orders', '0016_alter_orders_chosen_truck_alter_orders_order_state_and_more'),
    ]

    operations = [
    ]
