# Generated by Django 5.0.4 on 2024-06-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_orders_chosen_truck_alter_orders_order_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned'), ('pickup', 'Pickup'), ('delivered', 'Delivered')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('multiple commodities', 'Multiple Commodities '), ('wood', 'Wood'), ('furniture', 'Furinture'), ('glass', 'Glass'), ('food', 'Food'), ('plastic&rubber', 'Plastic and Rubber'), ('appliances', 'Appliances')], default='plastic&rubber', max_length=200),
        ),
    ]
