# Generated by Django 5.0.4 on 2024-06-19 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_merge_20240619_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(2, 'large truck'), (4, 'tricycle'), (3, 'special large truck'), (1, 'small truck')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('confirmed', 'Confirmed'), ('pickup', 'Pickup'), ('unassigned', 'Unassigned'), ('assigned', 'Assigned')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('furniture', 'Furinture'), ('wood', 'Wood'), ('appliances', 'Appliances'), ('glass', 'Glass'), ('plastic&rubber', 'Plastic and Rubber'), ('multiple commodities', 'Multiple Commodities '), ('food', 'Food')], default='plastic&rubber', max_length=200),
        ),
    ]
