# Generated by Django 5.0.4 on 2024-06-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_orders_order_state_alter_orders_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='need_labor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='need_packing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('pickup', 'Pickup'), ('delivered', 'Delivered')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('appliances', 'Appliances'), ('wood', 'Wood'), ('plastic&rubber', 'Plastic and Rubber'), ('food', 'Food'), ('furniture', 'Furinture'), ('glass', 'Glass'), ('multiple commodities', 'Multiple Commodities ')], default='plastic&rubber', max_length=200),
        ),
    ]
