# Generated by Django 5.0.4 on 2024-06-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_orders_need_labor_alter_orders_need_packing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='commodity_image',
        ),
        migrations.AlterField(
            model_name='orders',
            name='chosen_truck',
            field=models.CharField(choices=[(3, 'special large truck'), (2, 'large truck'), (1, 'small truck'), (4, 'tricycle')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_state',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('confirmed', 'Confirmed'), ('pickup', 'Pickup'), ('assigned', 'Assigned'), ('delivered', 'Delivered')], default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='type',
            field=models.CharField(choices=[('wood', 'Wood'), ('plastic&rubber', 'Plastic and Rubber'), ('furniture', 'Furinture'), ('food', 'Food'), ('appliances', 'Appliances'), ('multiple commodities', 'Multiple Commodities '), ('glass', 'Glass')], default='plastic&rubber', max_length=200),
        ),
    ]
